name: simple_parking
description: NaviParking Test
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.3
  provider: ^5.0.0
  dartz: ^0.9.2
  mockito: ^5.0.5
  data_connection_checker: ^0.3.4
  get_it: ^6.1.1
  equatable: ^2.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true